app:
  title: Acme Corp1 IDP
  baseUrl: ${APP_BASE_URL}

organization:
  name: Acme Corp

backend:
  baseUrl: ${BACKEND_BASE_URL}
  listen:
    port: 7007
  auth:
    dangerouslyDisableDefaultAuthPolicy: true
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: ${APP_BASE_URL}
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
  cache:
    store: redis
    redis:
      url: redis://${REDIS_HOST}:${REDIS_PORT}

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

proxy: {}

techdocs:
  builder: local
  generator:
    runIn: local
  publisher:
    type: local

auth:
  providers:
    guest: {}

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, Domain, Group, User]
  locations:
    - type: file
      target: ./catalog/all.yaml
