apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform
  description: Platform engineering
spec:
  type: team
  profile:
    displayName: Platform
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  profile:
    displayName: Guest
  memberOf:
    - platform
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: developer-portal
  description: Local Backstage system
spec:
  owner: group:default/platform
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: Local Backstage instance
spec:
  type: website
  lifecycle: experimental
  owner: group:default/platform
  system: developer-portal
